name: src
description: "official muppin project - version early access"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_messaging: ^14.7.8
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.15.2
  google_sign_in: ^6.2.0
  awesome_dialog: ^3.1.0
  mailer: ^6.0.1
  cached_network_image: ^3.3.0
  connectivity: ^3.0.6
  emoji_picker_flutter: ^1.6.3
  image_picker: ^1.0.5
  firebase_storage: ^11.5.6
  flutter_staggered_animations: ^1.1.1
  image_gallery_saver: ^2.0.3
  dio: ^5.4.0
  swipe_to: ^1.0.5
  image_cropper: ^5.0.1
  url_launcher: ^6.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/default.png
    - assets/images/chat_bg.jpeg
    - assets/images/camera.png
    - assets/images/gallery.png
    - assets/images/msgempty.png
    - assets/images/building.png
    - assets/images/notificationempty.png

    - assets/badges/bughunter.png
    - assets/badges/erkendonemdestekcisi.png
    - assets/badges/premium.png
    - assets/badges/admin.png

    - assets/socials/instagram.png
    - assets/socials/twitter.png
    - assets/socials/youtube.png
    - assets/socials/discord.png